# Generated by Django 4.0.4 on 2022-05-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_photo_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
