# Generated by Django 4.0.4 on 2022-05-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_photo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='products',
            new_name='product',
        ),
    ]
