# Generated by Django 4.0.4 on 2022-05-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_products_photo_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file_path',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='products.product'),
        ),
    ]
